const flightFacts  = [
  "The average price of building an airplane ranges from $90 to $115M, depending on its size and capability.",
  "With a wingspan of 288 feet (87 m), a weight of 710 tons, and six engines, the Antonov An-225 Mriya was the largest operational airplane until Russia destroyed it in 2022.",
  "The plane’s famous “black box” is not black but orange because it’d be more visible in case of an accident.",
  "The commander and the first officer aren’t allowed to eat the same food. That’s because if something is wrong with the meal, the other pilot can still operate the plane.",
  "Although it seems airplanes need two engines, some can fly with only one engine for almost five hours.",
  "The main components of airplanes are titanium, steel, and aluminum.",
  "The probability of dying in a plane crash is one in 11M, while the possibility of dying in a car crash is one in 5K. That means your chances of dying in a car accident are 2.2K times higher than in a plane crash.",
  "The New York to Abu Dhabi flight with Etihad can cost travelers ~$64K (one-way).",
  "While most commercial aircraft reach a maximum of 559 mph (899 km), the Lockheed SR-71 (today’s fastest aircraft) can go as fast as 2,100 mph (3,379 km).",
  "The Airbus A380 is the largest passenger plane that can carry up to 850 people.",
  "43% of pilots admitted to falling asleep while flying.",
  "The altitude at which commercial aircraft usually fly is between 33,000 and 42,000 feet (10 and 12.8 km). It’s called cruising altitude.",
  "The lifespan of a passenger airplane is ~25 years, after which it’s destined for cargo use.",
  "The longest non-stop flight from Seoul (South Korea) to Buenos Aires (Argentina) lasts 20 hours and 19 minutes.",
  "Commercial airplanes are struck by lightning an average of two times yearly. Even so, aircraft are prepared to withstand a discharge of that power and avoid significant damage.",
  "The first ever flight lasted only 12 seconds and covered 121 feet (36 m).",
  "It’s estimated that 96K planes are in the air every day.",
  "The world’s shortest commercial flight lasts only 80 seconds and travels only 16.77 miles (26.9 km)—the distance between the islands of Papa Westray and Westray in Scotland.",
  "It’s estimated there are between 1.5 and 2.3M pilots worldwide. The country with the most pilots is the USA (730K pilots).",
  "The word airplane comes from the Greek “aēr,” meaning air, and the Latin term “planus,” which stands for level.",
  "At the age of 86 (and with 65+ years in aviation), Bette Nash is considered the most experienced flight attendant.",
  "On May 15, 1930, Ellen Church became the first female flight attendant, working a 20-hour flight from San Francisco to Chicago.",
  "College Park Airport in the city of College Park (Maryland, US) is the world’s oldest airport in operation, established in 1909.",
  "The first transatlantic flight took place on June 14, 1919.",
  "New York International Airport opened in 1948 and was known as Idlewild Airport.",
  "There were about 6K reports of unruly passengers in 2021 in the US alone.",
  "The flight crew has the legal authority to use handcuffs if de-escalation tactics don’t work and a passenger threatens the aircraft’s safety.",
  "Oxygen masks don’t last for the entire flight in case of cabin depressurization. They can only provide air to passengers for ~15 minutes.",
  "61% of passengers who sleep on a plane rate their sleep quality as poor or below average.",
  "The largest private jet belongs to Joseph Lau and is valued at $367M. It has an interior of 1,460 square feet (135 sq m) and a spiral staircase connecting the two levels.",
  "The most expensive private jet in the world is Saudi Prince Alwaleed bin Talal’s Airbus A380. It’s worth over $500M.",
  "There are 22K private aircraft worldwide today.",
  "Private light aircraft suffer an average of five daily accidents, resulting in ~500 fatalities annually in the US.",
  "The country with the most private jets is the USA (12K), followed by Mexico at 950.",
  "There are private jets with saunas, jacuzzis, and other luxury amenities. Thus, Sir Elton John’s $89M private jet features a piano he uses to practice before his musical tours.",
  "Niger, the most impoverished nation in the world, has 45 private aircraft, with rentals costing about $4K per hour.",
  "The price of buying a private jet hangar varies between $30K and several million dollars.",
  "FedEx has the biggest number of airplanes for cargo transportation, with almost 700 aircraft.",
  "While the United States has the most airports (19,622), there are 26 countries with only one airport, including Gambia and Barbados.",
  "There were 12 fatal commercial aircraft accidents in 2022, causing a total of 229 deaths.",
  "Mumbai’s Chhatrapati Shivaji International Airport managed to host 969 take-offs and landings within 24 hours, setting a new record.",
  "Princess Juliana International Airport in Saint Martin is one of the most challenging airfields to land a plane. The airport is extremely close to Maho Beach, and the runway is short and close to the water.",
  "Antarctica has 20 airports, but they all have limited and non-public access.",
  "Airports in London, Dubai, and Singapore are among the most secure in the world.",
  "Although it’s difficult to know for sure, North Korea has 78 usable airfields, all of which are restricted to tourists.",
  "Although most airports have only one or two runways for take-off and landing, there are airports with more than four runways. Chicago airport has eight operational runways.",
  "Yrausquin Airport is the world’s smallest commercial airport, located on the island of Saba in the Caribbean, having the shortest commercial runway with a length of 1,312 feet (400 m)."
];

// Export for use in other files (Node.js style)
export default flightFacts;
